name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Following https://github.com/leanprover/lean-action
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
